# Generated by Django 3.0.7 on 2020-06-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('body', models.CharField(max_length=1000)),
                ('datetime', models.DateTimeField(auto_now=True)),
                ('last_modified', models.DateTimeField()),
            ],
        ),
    ]
